development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: coach_db_test
  suffix: development
  username:
  password:

# development: &development
#   protocol: 'http'
#   host: xan.iriscouch.com
#   port: 5984
#   prefix: coach_db_test
#   suffix: development
#   username:
#   password:
# 
test:
  <<: *development
  suffix: test

production:
  protocol: 'https'
  host: localhost
  port: 5984
  prefix: coach_db_test
  suffix: production
  username: root
  password: 123